export const ADDMOVIE = 'ADDMOVIE'
export const DELETEMOVIE = 'DELETEMOVIE'
export const UPDATEMOVIE = 'UPDATEMOVIE'
export const FILTERMOVIE = 'FILTERMOVIE'

export const ADDMOVIEFAVORITE = 'ADDMOVIEFAVORITE'
export const DELETEMOVIEFAVORITE = 'DELETEMOVIEFAVORITE'

export const ADDGENRES = 'ADDGENRES'
export const REMOVEGENRES = 'REMOVEGENRES'
